print("===================================")
print("       CAESAR CIPHER TOOL")
print("===================================")
print()
print("Welcome to the Casear Cipher Tool")
print()
print("Enter [1] for Encrypt")
print("Enter [2] for Decrypt")
print("Enter [3] for Brute Force")
print("Enter [4] to Exit")

choice = input("Select an option ")
print ("You selected:", choice)